# Generated by Django 5.1.7 on 2025-03-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "username",
                    models.CharField(default="", max_length=255, verbose_name="用户名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=255, verbose_name="密码"),
                ),
                (
                    "sex",
                    models.CharField(default="", max_length=255, verbose_name="性别"),
                ),
                (
                    "address",
                    models.CharField(default="", max_length=255, verbose_name="地址"),
                ),
                (
                    "avatar",
                    models.CharField(
                        default="avatar/default.jpg",
                        max_length=255,
                        verbose_name="头像",
                    ),
                ),
                (
                    "textarea",
                    models.TextField(
                        default="", max_length=255, verbose_name="个性签名"
                    ),
                ),
                (
                    "creatname",
                    models.DateField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={
                "db_table": "history",
            },
        ),
    ]
