# Generated by Django 5.1.7 on 2025-03-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="textarea",
            field=models.TextField(
                default="这个人很懒，什么都没有留下",
                max_length=255,
                verbose_name="个性签名",
            ),
        ),
    ]
